FormBot.Main/Controllers/FormBotReportController.cs
using FormBot.BAL;
using FormBot.BAL.Service;
using FormBot.Entity;
using FormBot.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Data;
using System.Text;
using System.IO;
using Newtonsoft.Json.Linq;
using FormBot.Entity.Dashboard;

namespace FormBot.Main.Controllers
{
    public class FormBotReportController : Controller
    {
        #region Properties
        private readonly IFormBotReportBAL _formBotReportService;
        private readonly IResellerBAL _resellerService;
        #endregion

        #region Constructor
        public FormBotReportController(IFormBotReportBAL formBotReportService, IResellerBAL resellerService)
        {
            this._formBotReportService = formBotReportService;
            this._resellerService = resellerService;
        }
        #endregion

        #region Event
        [UserAuthorization]
        public ActionResult Index()
        {
            FormBotReport model = new FormBotReport();
            var lstReport = _formBotReportService.GetFormBotReportDrp();
            lstReport = lstReport.Where(s => s.ReportName != "SE User Level Report" && s.ReportName != "SSC, SE Jobs Detail Report").ToList();
            model.lstReport = lstReport;
            return View(model);
        }
        public ActionResult _NonTradeJobs()
        {
            FormBotReport model = new FormBotReport();
            return View(model);
        }

        /// <summary>
        /// get solar company.
        /// </summary>
        /// <param name="hdnResellers">hdnResellers.</param>
        /// <returns>action result</returns>
        public ActionResult _SolarCompany(string hdnResellers = "")
        {
            FormBotReport model = new FormBotReport();
            var lstSolarCompany = _formBotReportService.GetSolarCompany("",hdnResellers);
            model.LstSolarCompany = lstSolarCompany;
            model.LstSolarCompanyAssignedUser = new List<SelectListItem>();
            return View(model);
        }

        /// <summary>
        /// get solar company For Active.
        /// </summary>
        /// <returns>action result</returns>
        public ActionResult _SolarCompanyForActive()
        {
            FormBotReport model = new FormBotReport();
            var lstSolarCompany = _formBotReportService.GetSolarCompany();
            model.LstSolarCompany = lstSolarCompany;
            model.LstSolarCompanyAssignedUser = new List<SelectListItem>();
            return View(model);
        }

        /// <summary>
        /// get preapproval status.
        /// </summary>
        /// <returns>action result</returns>
        public ActionResult _Preapproval()
        {
            FormBotReport model = new FormBotReport();
            var lstPreapprovalStatus = _formBotReportService.GetPreapprovalStatus();
            model.LstPreapprovalStatus = lstPreapprovalStatus;
            model.LstPreapprovalStatusAssigned = new List<SelectListItem>();
            return View(model);
        }

        /// <summary>
        /// get connection status.
        /// </summary>
        /// <returns>action result</returns>
        public ActionResult _Connection()
        {
            FormBotReport model = new FormBotReport();
            var lstConnectionStatus = _formBotReportService.GetConnectionStatus();
            model.LstConnectionStatus = lstConnectionStatus;
            model.LstConnectionStatusAssigned = new List<SelectListItem>();
            return View(model);
        }

        /// <summary>
        /// _STCSubmission
        /// </summary>
        /// <param name="report">report</param>
        /// <returns>ActionResult</returns>
        public ActionResult _STCSubmission(string report = "")
        {
            FormBotReport model = new FormBotReport();
            var lstStcSubmissionStatus = _formBotReportService.GetSTCSubmissionStatus();
            if (!string.IsNullOrEmpty(report) && report.ToLower() == "jobstatusbardetailsreport")
                model.LstSTCSubmissionStatus = lstStcSubmissionStatus.Where(s => s.Text.ToLower() != "not yet submitted" && s.Text.ToLower() != "submit to trade").ToList();
            else
                model.LstSTCSubmissionStatus = lstStcSubmissionStatus;
            model.LstSTCSubmissionStatusAssigned = new List<SelectListItem>();
            return View(model);
        }

        /// <summary>
        /// the users list.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>action result</returns>
        public ActionResult _UsersList(string id)
        {
            FormBotReport model = new FormBotReport();
            if (id == "4")
            {
                model.LstUsers = _formBotReportService.GetSolarCompany();
            }
            else
            {
                model.LstUsers = _formBotReportService.GetFormBotUser(Convert.ToInt32(id));
            }
            model.LstSolarCompanyAssignedUser = new List<SelectListItem>();
            return View(model);
        }

        /// <summary>
        /// the SSC view.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>action result</returns>
        public ActionResult _SSCView(string id)
        {
            FormBotReport model = new FormBotReport();
            model.LstSSCUsers = _formBotReportService.GetFormBotUser(Convert.ToInt32(id));
            model.LstSSCAssignedUser = new List<SelectListItem>();
            return View(model);
        }

        /// <summary>
        /// the sc view.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>action result</returns>
        public ActionResult _SCView(string id)
        {
            FormBotReport model = new FormBotReport();
            if (ProjectSession.UserTypeId == 9)
                model.LstSCUsers = _formBotReportService.GetFormBotUser(Convert.ToInt32(id), string.Empty, ProjectSession.LoggedInUserId);
            else
                model.LstSCUsers = _formBotReportService.GetFormBotUser(Convert.ToInt32(id));

            //model.LstSCAssignedUser = new List<SelectListItem>();
            model.LstSCAssignedUser = model.LstSCUsers.Where(x => x.Value == ProjectSession.LoggedInUserId.ToString()).Select(X => X).ToList();
            model.LstSCUsers = model.LstSCUsers.Where(x => x.Value != ProjectSession.LoggedInUserId.ToString()).Select(X => X).ToList();
            return View(model);
        }

        /// <summary>
        /// the se view.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>action result</returns>
        public ActionResult _SEView(string id)
        {
            FormBotReport model = new FormBotReport();
            if (ProjectSession.UserTypeId == 7)
                model.LstSEUsers = _formBotReportService.GetFormBotUser(Convert.ToInt32(id), string.Empty, ProjectSession.LoggedInUserId);
            else
                model.LstSEUsers = _formBotReportService.GetFormBotUser(Convert.ToInt32(id)); 

            //model.LstSEAssignedUser = new List<SelectListItem>();
            model.LstSEAssignedUser = model.LstSEUsers.Where(x => x.Value == ProjectSession.LoggedInUserId.ToString()).Select(X => X).ToList();
            model.LstSEUsers = model.LstSEUsers.Where(x => x.Value != ProjectSession.LoggedInUserId.ToString()).Select(X => X).ToList();
            return View(model);
        }

        public ActionResult _SWHView(string id)
        {
            FormBotReport model = new FormBotReport();
            if (ProjectSession.UserTypeId == 10)
                model.LstSWHUsers = _formBotReportService.GetFormBotUser(Convert.ToInt32(id), string.Empty, ProjectSession.LoggedInUserId);
            else
                model.LstSWHUsers = _formBotReportService.GetFormBotUser(Convert.ToInt32(id)); // FOR SE - 7
            
            model.LstSWHAssignedUser = model.LstSWHUsers.Where(x => x.Value == ProjectSession.LoggedInUserId.ToString()).Select(X => X).ToList();
            model.LstSWHUsers = model.LstSWHUsers.Where(x => x.Value != ProjectSession.LoggedInUserId.ToString()).Select(X => X).ToList();
            return View(model);
        }

        /// <summary>
        /// the reseller details.
        /// </summary>
        /// <returns>action result</returns>
        public ActionResult _Reseller()
        {
            FormBotReport model = new FormBotReport();
            model.LstResellerUsers = _resellerService.GetData(null).Select(a => new SelectListItem { Text = a.ResellerName, Value = a.ResellerID.ToString() }).ToList();
            model.LstResellerAssignedUser = new List<SelectListItem>();
            return View(model);
        }
        /// <summary>
        /// the reseller For Active.
        /// </summary>
        /// <returns>action result</returns>
        public ActionResult ResellerForActive()
        {
            FormBotReport model = new FormBotReport();
            model.LstResellerUsers = _resellerService.GetData(null).Select(a => new SelectListItem { Text = a.ResellerName, Value = a.ResellerID.ToString() }).ToList();
            model.LstResellerAssignedUser = new List<SelectListItem>();
            return View(model);
        }

        /// <summary>
        /// the sco view
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="hdnSolarCompanies">hdnSolarCompanies</param>
        /// <returns>ActionResult</returns>
        public ActionResult _SCOView(string id, string hdnSolarCompanies = "")
        {
            FormBotReport model = new FormBotReport();
            model.LstSCOUsers = _formBotReportService.GetFormBotUser(Convert.ToInt32(id), (string.IsNullOrEmpty(hdnSolarCompanies) || hdnSolarCompanies == "undefined") ? "" : hdnSolarCompanies, ProjectSession.LoggedInUserId);
            model.LstSCOAssignedUser = new List<SelectListItem>();
            return View(model);
        }

FormBot.Main/Views/FormBotReport/_FCOView.cshtml
@model FormBot.Entity.FormBotReport
@{
    Layout = null;
}
<input type="hidden" name="FCOBit" value="10" id="FCOBit" />
<input type="hidden" name="minFCO" value="1" id="minFCO" />

<div class="row malti-list">
    <div class="col-sm-5 ">
        <div class="form-group">
            <div class="col-md-6 col-sm-6 " style="width:100%;padding:0;">
                @Html.ListBoxFor(m => m.LstFCO, new MultiSelectList(Model.LstFCOUsers, "Value", "Text"), new { id = "LstFCO", @class = "form-control", style = "padding:0px;height: 400px;", @tabindex = 2 })
            </div>
        </div>
    </div>
    <div class=" col-sm-2 tra-btn">
        <div class="form-group">
            <a id="btnLtoR_FCO" href="javascript:void(0);" class="linkbutton">
                <input type="button" value=">>" class="btn btn-info primary" tabindex="3" />
            </a>
            <a id="btnRtoL_FCO" href="javascript:void(0);" class="linkbutton">
                <input type="button" value="<<" class="btn btn-info primary" tabindex="4" />
            </a>
        </div>
    </div>
    <div class="col-sm-5">
        <div class="form-group">
            <div class="col-md-6 col-sm-6 custinput" style="width: 100%;padding: 0;">
                @Html.ListBoxFor(m => m.FormBotFCOAssignedUser, new MultiSelectList(Model.LstFCOAssignedUser, "Value", "Text"), new { id = "LstFCOAssignedUser", @class = "form-control", style = "padding:0px;height: 400px;", @tabindex = 5 })
                @Html.HiddenFor(m => m.hdnFormBotFCOAssignedUser, new { id = "hdnFCO" })
            </div>
        </div>
    </div>
</div>
<div class="form-group defaultFormBot tab_bottomrow">
    <input type="button" name="SaveMapping" value="Save" autofocus class="primary save_ic" id="btnFCOSave" tabindex="6">
    <div class="default btn icon-btn">
        <span class="sprite-img reset_ic"></span>
        <input type="button" value="Clear" id="btnCancelFCO" class="" tabindex="7">
        </div>
    </div>

<script type="text/javascript">

    $(document).on("click", "#btnLtoR_FCO", function () {
        if (parseInt($('#FCOBit').val()) == 0) {
            $('#LstFCO option:selected').each(function () {
                $(this).remove().appendTo("#LstFCOAssignedUser");
            });
            $('#AvailableFCO').html($('#LstFCOAssignedUser option').length);
        }
        else {
            var SCA_Acc = (($('#LstFCO option:selected').length + $('#LstFCOAssignedUser option').length) <= parseInt($('#FCOBit').val()));
            if (SCA_Acc) {
                var LstSCA_Acc = $('#LstFCOAssignedUser option').length < parseInt($('#FCOBit').val());
                if (LstSCA_Acc) {
                    $('#LstFCO option:selected').each(function () {
                        $(this).remove().appendTo("#LstFCOAssignedUser");
                    });
                    var max = $('#FCOBit').val();
                    $('#AvailableFCO').html($('#LstFCOAssignedUser option').length);
                }
                if (($('#LstFCOAssignedUser option').length == parseInt($('#FCOBit').val()))) {
                    $('#btnLtoR_FCO').css('opacity', '0.5');
                    $('#btnLtoR_FCO').css('cursor', 'auto');
                }
                else {
                    $('#btnLtoR_FCO').css('opacity', '1');
                    $('#btnLtoR_FCO').css('cursor', 'poiter');
                }
            }
        }
    });

    $(document).on("click", "#btnRtoL_FCO", function () {
        $('#LstFCOAssignedUser option:selected').each(function () {
            $(this).remove().appendTo("#LstFCO");
        });
        var max = $('#FCOBit').val();
        if (max > 0) {
            $('#AvailableFCO').html($('#LstFCOAssignedUser option').length);
        } else {
            $('#AvailableFCO').html($('#LstFCOAssignedUser option').length);
        }
        if (($('#LstFCOAssignedUser option').length < parseInt($('#FCOBit').val()))) {
            $('#btnLtoR_FCO').css('opacity', '1');
            $('#btnLtoR_FCO').css('cursor', 'poiter');
        }
        else {
            $('#btnLtoR_FCO').css('opacity', '0.5');
            $('#btnLtoR_FCO').css('cursor', 'auto');
        }
    });

    //$(document).on("click", "#closeFCO", function () {
    //    $('#popupFCO').modal('hide');
    //    $('#cntFCO').html($('#LstFCOAssignedUser option').length);
    //});

    $(document).on("click", "#btnFCOSave", function () {
        var strAssignedAttendeeList = [];
        $('#LstFCOAssignedUser option').each(function (i) {
            strAssignedAttendeeList.push($(this).val().trim());
        });
        if ($('#minFCO').val() > 0) {
            document.getElementById('btnJobStatusBarReport').style.pointerEvents = 'auto';
            $('#btnJobStatusBarReport').css('opacity', '1');
            $("#errorMsgRegion").hide();
        }
        if ($('#minFCO').val() > 0 && $('#LstFCOAssignedUser option').length == 0) {
            document.getElementById('btnJobStatusBarReport').style.pointerEvents = 'none';
            $('#btnJobStatusBarReport').css('opacity', '0.5');
        }
        if (($('#LstFCOAssignedUser option').length <= parseInt($('#FCOBit').val()))) {
            document.getElementById('btnJobStatusBarReport').style.pointerEvents = 'auto';
            $('#btnJobStatusBarReport').css('opacity', '1');
            $("#errorMsgRegion").hide();
        }
        if ($('#minFCO').val() == 1 && $('#LstFCOAssignedUser option').length == 0) {
            document.getElementById('btnJobStatusBarReport').style.pointerEvents = 'none';
            $('#btnJobStatusBarReport').css('opacity', '0.5');
        }
        $("#hdnFCO").val(strAssignedAttendeeList);
        $('#cntFCO').html($('#LstFCOAssignedUser option').length);
        $('#popupFCO').modal('hide');
    });

    $(document).on("click", "#btnCancelFCO", function () {
        $('#LstFCOAssignedUser option').each(function () {
            $(this).remove().appendTo("#LstFCO");
        });
        var max = $('#FCOBit').val();
        if (max > 0) {
            $('#AvailableFCO').html($('#LstFCOAssignedUser option').length);
        } else {
            $('#AvailableFCO').html($('#LstFCOAssignedUser option').length);
        }
        if (($('#LstFCOAssignedUser option').length < parseInt($('#FCOBit').val()))) {
            $('#btnLtoR_FCO').css('opacity', '1');
            $('#btnLtoR_FCO').css('cursor', 'poiter');
        }
        else {
            $('#btnLtoR_FCO').css('opacity', '0.5');
            $('#btnLtoR_FCO').css('cursor', 'auto');
        }
        $("#hdnFCO").val('');
    });

    $(document).on("click", "#closeFCO", function () {
        var strAssignedAttendeeList = [];
        $('#LstFCOAssignedUser option').each(function (i) {
            strAssignedAttendeeList.push($(this).val().trim());
        });
        if ($('#minFCO').val() > 0) {
            document.getElementById('btnJobStatusBarReport').style.pointerEvents = 'auto';
            $('#btnJobStatusBarReport').css('opacity', '1');
            $("#errorMsgRegion").hide();
        }
        if ($('#minFCO').val() > 0 && $('#LstFCOAssignedUser option').length == 0) {
            document.getElementById('btnJobStatusBarReport').style.pointerEvents = 'none';
            $('#btnJobStatusBarReport').css('opacity', '0.5');
        }
        if (($('#LstFCOAssignedUser option').length <= parseInt($('#FCOBit').val()))) {
            document.getElementById('btnJobStatusBarReport').style.pointerEvents = 'auto';
            $('#btnJobStatusBarReport').css('opacity', '1');
            $("#errorMsgRegion").hide();
        }
        if ($('#minFCO').val() == 1 && $('#LstFCOAssignedUser option').length == 0) {
            document.getElementById('btnJobStatusBarReport').style.pointerEvents = 'none';
            $('#btnJobStatusBarReport').css('opacity', '0.5');
        }
        $("#hdnFCO").val(strAssignedAttendeeList);
        $('#cntFCO').html($('#LstFCOAssignedUser option').length);
        $('#popupFCO').modal('hide');
    });
</script>
<style>
    .malti-list .tra-btn {
        margin-top: 140px;
    }
</style>

FormBot.Main/Views/FormBotReport/_SEUserLevelReports.cshtml
@model FormBot.Entity.FormBotReport
@{
    Layout = null;
}
<div class="form-group">
    <div class="rep_spacer"></div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label">Start Date:</label>
                <div class="input-group">
                    @Html.TextBoxFor(m => m.StartDate, new { @class = "form-control", @readonly = "readonly", @placeholder = "Start", @id = "txtFromDate", @tabindex = "7" })
                    <span class="input-group-addon"><img src="@Url.Content("~/images/ic-cal.png")" alt=""></span>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label">End Date:</label>
                <div class="input-group">
                    @Html.TextBoxFor(m => m.EndDate, new { @class = "form-control", @readonly = "readonly", @placeholder = "End", @id = "txtToDate", @tabindex = "8" })
                    <span class="input-group-addon"><img src="@Url.Content("~/images/ic-cal.png")" alt=""></span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="rep_spacer"></div>
    <div class="form-group">
        <label>Date Grouping:</label>
        @Html.DropDownListFor(m => m.TimePeriod, new List<SelectListItem>
                                     {
                                        new SelectListItem{ Text="Daily", Value = "1" },
                                        new SelectListItem{ Text="Weekly", Value = "2" },
                                        new SelectListItem{ Text="Monthly", Value = "3" },
                                         new SelectListItem{ Text="All Time", Value = "4" },
                                     }, new { @id = "drpTimePeriod", @class = "form-control" }
                            )
    </div>
</div>
<div class="rep-btn">
    <input type="button" onclick="RunReport();" tabindex="18" id="btnJobStatusBarReport" class="primary report_ic" autofocus="" value="Run Report" name="Submit" style="pointer-events: auto; opacity: 1;">
    <div class="default btn icon-btn" onclick="ResetSearchFilters();">
        <span class="sprite-img reset_ic"></span>
        <input type="button" id="btnReset" value="Reset Filters" class="">
    </div>
    </div>

<script type="text/javascript">
    var dateFormat = '@FormBot.Helper.ProjectConfiguration.GetDateFormat';
    var dateFormatMoment = '@FormBot.Helper.ProjectConfiguration.GetDateFormat.ToUpper()';
    $(document).ready(function () {
        document.getElementById('btnJobStatusBarReport').style.pointerEvents = 'none';
        $('#btnJobStatusBarReport').css('opacity', '0.5');
        $('#txtFromDate').datepicker({
            format: dateFormat,
            autoclose: true
        }).on('changeDate', function () {
            if ($("#txtToDate").val() != '') {
                var fromDate = new Date(ConvertDateToTick($("#txtFromDate").val(), dateFormat));
                var toDate = new Date(ConvertDateToTick($("#txtToDate").val(), dateFormat));
                if (fromDate > toDate) {
                    $("#txtToDate").val('');
                    document.getElementById('btnJobStatusBarReport').style.pointerEvents = 'none';
                    $('#btnJobStatusBarReport').css('opacity', '0.5');
                }
            }

            var tickStartDate = ConvertDateToTick($("#txtFromDate").val(), dateFormat);
            tDate = moment(tickStartDate).format("MM/DD/YYYY");
            if ($('#txtToDate').data('datepicker')) {
                $('#txtToDate').data('datepicker').setStartDate(new Date(tDate));
            }
        });
        $("#txtToDate").datepicker({
            format: dateFormat,
            autoclose: true
        });
        $('#txtFromDate').val('');
        $('#txtToDate').val('');
    });

    $("#txtToDate").change(function () {
        if ($("#txtToDate").val() != '') {
            document.getElementById('btnJobStatusBarReport').style.pointerEvents = 'auto';
            $('#btnJobStatusBarReport').css('opacity', '1');
        }
    });

    function RunReport() {
        var data = JSON.stringify($('#FormBotReportDetails').serializeToJson());
        $.ajax({
            url: '@Url.Action("GetSEUserLevelReportsList", "FormBotReport")',
            type: "POST",
            dataType: "json",
            data: data,
            async: true,
            processData: false,
            cache: false,
            contentType: 'application/json; charset=utf-8',
            success: function (result) {
                $('#divGrid').show();
                BindGrid(result);
            },
            error: function (e) {
                console.log(e);
            }
        });
        return false;
    }

    $.fn.serializeToJson = function () {
        var $form = $(this[0]);

        var items = $form.serializeArray();
        var returnObj = {};
        var nestedObjectNames = [];

        $.each(items, function (i, item) {
            //Split nested objects and assign properties
            //You may want to make this recursive - currently only works one step deep, but that's all I need
            if (item.name.indexOf('.') != -1) {
                var nameArray = item.name.split('.');
                if (nestedObjectNames.indexOf(nameArray[0]) < 0) {
                    nestedObjectNames.push(nameArray[0]);
                }
                var tempObj = returnObj[nestedObjectNames[nestedObjectNames.indexOf(nameArray[0])]] || {};
                if (!tempObj[nameArray[1]]) {
                    tempObj[nameArray[1]] = item.value;
                }
                returnObj[nestedObjectNames[nestedObjectNames.indexOf(nameArray[0])]] = tempObj;
            } else if (!returnObj[item.name]) {
                returnObj[item.name] = item.value;
            }
        });

        return returnObj;
    };

    function BindGrid(result) {
        $('#chartbox').hide();
        if ($('#datatable')) {
            var table = $('#datatable').DataTable();
            table.destroy();
        }
        var tableHeaders = '';
        var tableFooters = '';
        var tableColumns = [];

        tableColumns.push("Start Date");
        tableColumns.push("Name");
        tableColumns.push("Total Job");
        tableColumns.push("Completed Job");
        tableColumns.push("OutStanding Job");
        tableFooters = '<th></th><th style="text-align:right;"></th><th></th><th></th><th></th>';

        $.each(tableColumns, function (i, val) {
            tableHeaders += "<th><span>" + val + "</span></th>";
        });
        $("#displayTable").empty();
        $("#displayTable").append('<table id="datatable" class="table table-hover"><thead><tr>' + tableHeaders + '</tr></thead><tfoot><tr>' + tableFooters + '</tr></tfoot></table>');

        getColumn($('#ReportID').val());

        $('#datatable').DataTable({
            data: result,
            paging: false,
            searching: false,
            retrieve: true,
            columns: columnsArray,
            dom: 'Bfrtip',
            buttons: [
                {
                    extend: 'excel',
                    footer: true
                }
            ],
            order: [[0, "asc"]],
            footerCallback: function (row, data, start, end, display) {
                if (data.toString() != "") {
                    var api = this.api(), data;
                    var intVal = function (i) {
                        return typeof i === 'string' ?
                            i * 1 :
                            typeof i === 'number' ?
                            i : 0;
                    };
                    NewTotal = api
                        .column(2)
                        .data()
                        .reduce(function (a, b) {
                            return intVal(a) + intVal(b);
                        }, 0);
                    PreApprovalTotal = api
                        .column(3)
                        .data()
                        .reduce(function (a, b) {
                            return intVal(a) + intVal(b);
                        }, 0);
                    NewInstallationTotal = api
                        .column(4)
                        .data()
                        .reduce(function (a, b) {
                            return intVal(a) + intVal(b);
                        }, 0);
                    // Update footer
                    $(api.column(2).footer()).html(
                        NewTotal
                    );
                    $(api.column(3).footer()).html(
                        PreApprovalTotal
                    );
                    $(api.column(4).footer()).html(
                        NewInstallationTotal
                    );
                    $(api.column(1).footer()).html(
                       'Total:'
                    );
                } else {
                    $('#datatable tfoot').remove();
                }
            }
        });
        $('#datatable_length').hide();
        $('#datatable_info').hide();
        //$('#datatable tr th').attr('class', 'sorting_disabled table-header');
        $('#datatable tbody tr td:nth-child(3)').attr('style', 'text-align:right;');
        $('#datatable tbody tr td:nth-child(4)').attr('style', 'text-align:right;');
        $('#datatable tbody tr td:nth-child(5)').attr('style', 'text-align:right;');

        $('#datatable thead tr th:nth-child(3)').attr('style', 'text-align:right;');
        $('#datatable thead tr th:nth-child(4)').attr('style', 'text-align:right;');
        $('#datatable thead tr th:nth-child(5)').attr('style', 'text-align:right;');

        $('#datatable tfoot tr th:nth-child(3)').attr('style', 'text-align:right;');
        $('#datatable tfoot tr th:nth-child(4)').attr('style', 'text-align:right;');
        $('#datatable tfoot tr th:nth-child(5)').attr('style', 'text-align:right;');

        $('#datatable th:first').attr('style', 'width:12% !important;');
        $('.buttons-excel').addClass('primary pull-right');
        $('.buttons-excel').html('<span>Export to Excel</span>');
    }

    function getColumn(id) {
        columnsArray = [
           {
               'data': 'StartDate',
               "render": function (result, type, full, meta) {
                   return ConvertToDate(result);
               },
               "orderable": true
           },
           {
               'data': 'FullName',
               "orderable": true
           },
           {
               'data': 'TotalJobs',
               "orderable": true
           },
           {
               'data': 'CompletedJobs',
               "orderable": true
           },
           {
               'data': 'OutStandingJobs',
               "orderable": true
           },
        ];
    }
    function ConvertToDate(data) {
        if (data != null) {
            var date = new Date(parseInt(data.replace('/Date(', '')));
            return ("0" + date.getDate()).slice(-2) + '/' + ("0" + (date.getMonth() + 1)).slice(-2) + '/' + date.getFullYear();
        }
        else {
            return '';
        }
    }
    function ResetSearchFilters() {
        $('#txtFromDate').val('');
        $('#txtToDate').val('');
        $('#drpTimePeriod').val('1');
        document.getElementById('btnJobStatusBarReport').style.pointerEvents = 'none';
        $('#btnJobStatusBarReport').css('opacity', '0.5');
    }
    function ConvertToDate(data) {
        if (data != null) {
            var date = new Date(parseInt(data.replace('/Date(', '')));
            return ("0" + date.getDate()).slice(-2) + '/' + ("0" + (date.getMonth() + 1)).slice(-2) + '/' + date.getFullYear();
        }
        else {
            return '';
        }
    }
</script>
<style>
    .table-header {
        border-bottom: 2px solid #ddd !important;
        color: #808080 !important;
        background-color: #f5f5f5;
    }

    #datatable {
        border: 3px solid #e4e4e4 !important;
    }

        #datatable thead tr {
            border: 3px solid #e4e4e4;
        }

        #datatable th {
            color: #383838 !important;
            font-family: "OpenSansSemibold" !important;
            font-size: 13px !important;
            background: #f8f8f8 none repeat scroll 0 0 !important;
            padding: 10px 9px !important;
        }

    .dt-button {
        margin-bottom: 5px;
    }

    /*.find_job_leftpanel.active {
        margin-left: -379px !important;
    }

    .jtoggle.active {
        right: -60px !important;
    }*/
</style>