FormBot.Main/Controllers/SpvLogController.cs
using FormBot.BAL.Service.SPV;
using FormBot.Entity.KendoGrid;
using FormBot.Entity.SPV;
using FormBot.Helper;
using Microsoft.VisualBasic.FileIO;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace FormBot.Main.Controllers
{
    //[UserAuthorization]
    public class SpvLogController : BaseController
    {
        #region Fields
        private readonly Logger _log;
        private readonly ISpvLogBAL _spvLog;
        #endregion
        #region Constructor
        public SpvLogController(ISpvLogBAL spvLog)
        {
            _log = new Logger();
            _spvLog = spvLog;
        }
        #endregion
        #region Method

        [UserAuthorization]
        // GET: SpvLog
        public ActionResult Index()
        {
            return View();
        }
        // POST: GetEndPointsList
        [HttpPost]
        public JsonResult GetEndPointList()
        {
            List<string> lstEndPoints = new List<string>();
            try
            {
                lstEndPoints = _spvLog.GetAllEndPointsNameFromSpvManufacturer().ToList();
            }
            catch (Exception ex)
            {
                _log.LogException(SystemEnums.Severity.Error, $"SpvLogController/GetEndPointList", ex);
            }
            return Json(lstEndPoints, JsonRequestBehavior.AllowGet);
        }
        // POST: GetSpvLogs
        /// <summary>
        /// Get Spv logs with filters.
        /// </summary>
        /// <param name="PageSize"></param>
        /// <param name="PageNumber"></param>
        /// <param name="SortCol"></param>
        /// <param name="SortDir"></param>
        /// <param name="ServiceAdministrator"></param>
        /// <param name="ResellerId"></param>
        /// <param name="SolarCompanyId"></param>
        /// <param name="JobReferenceOrId"></param>
        /// <param name="PVDSWHcode"></param>
        /// <param name="SPVMethod"></param>
        /// <param name="VerificationStatus"></param>
        /// <param name="ResponseCode"></param>
        /// <param name="Manufacturer"></param>
        /// <param name="ModelNumber"></param>
        /// <param name="SerialNumer"></param>
        /// <param name="FromRequestDate"></param>
        /// <param name="ToRequestDate"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetSpvLogs(int skip, string take, string pageSize, int page,
            string ServiceAdministrator, int ResellerId, int? SolarCompanyId = null, string JobReferenceOrId = null, string PVDSWHcode = null, int? SPVMethod = null, int? VerificationStatus = null, string ResponseCode = null, string Manufacturer = null, string ModelNumber = null, string SerialNumer = null, DateTime? FromRequestDate = null, DateTime? ToRequestDate = null, List<KendoGridSorting> sort = null)
        {
            try
            {
                string SortCol = "", SortDir = "";
                if(sort != null)
                    if(sort.Any())
                    {
                        SortCol = sort.FirstOrDefault().Field;
                        SortDir = sort.FirstOrDefault().Dir;
                    }
                //string cacheKey = string.Format(CacheConfiguration.SpvLogList, Convert.ToInt32(pageSize), page, SortCol, SortDir, ServiceAdministrator, ResellerId, SolarCompanyId, JobReferenceOrId, PVDSWHcode, SPVMethod, VerificationStatus, ResponseCode, Manufacturer, ModelNumber, SerialNumer, FromRequestDate, ToRequestDate);
                List<SpvLog> lstSpvLogs = 
                    //CacheConfiguration.Get<List<SpvLog>>(cacheKey, () =>
                    //{
                    //    return 
                        _spvLog.GetSpvLogs(Convert.ToInt32(pageSize), page, SortCol, SortDir, ServiceAdministrator, ResellerId, SolarCompanyId, JobReferenceOrId, PVDSWHcode, SPVMethod, VerificationStatus, ResponseCode, Manufacturer, ModelNumber, SerialNumer, FromRequestDate, ToRequestDate).ToList();
                    //});

                return Json(new { total = (lstSpvLogs.Any() ? lstSpvLogs.FirstOrDefault().TotalRecordCount : 0), data = lstSpvLogs }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                _log.LogException(SystemEnums.Severity.Error, $"SpvLogController/GetSpvLogs", ex);
                return Json(new { total = 0, data = new List<dynamic>() }, JsonRequestBehavior.AllowGet);
            }
        }
        /// <summary>
        /// Get all spv log data with filters and export in csv .
        /// </summary>
        /// <param name="ServiceAdministrator"></param>
        /// <param name="ResellerId"></param>
        /// <param name="SolarCompanyId"></param>
        /// <param name="JobReferenceOrId"></param>
        /// <param name="PVDSWHcode"></param>
        /// <param name="SPVMethod"></param>
        /// <param name="VerificationStatus"></param>
        /// <param name="ResponseCode"></param>
        /// <param name="Manufacturer"></param>
        /// <param name="ModelNumber"></param>
        /// <param name="SerialNumer"></param>
        /// <param name="FromRequestDate"></param>
        /// <param name="ToRequestDate"></param>
        /// <returns></returns>
        public void ExportCSVForSPVLog(string ServiceAdministrator, int? ResellerId, int? SolarCompanyId = null, string JobReferenceOrId = null, string PVDSWHcode = null, int? SPVMethod = null, int? VerificationStatus = null, string ResponseCode = null, string Manufacturer = null, string ModelNumber = null, string SerialNumer = null, DateTime? FromRequestDate = null, DateTime? ToRequestDate = null, bool IsWithoutSCA = false, string ResellerName = null, string SolarCompanyName = null)
        {
            try
            {

                string ServiceAdministratorName = "Service Administrator:" + ServiceAdministrator;
                string SolarCompanyname = SolarCompanyId == -1 ? "All" : SolarCompanyName;
                string SpvMethod = SPVMethod == -1 ? "All" : SPVMethod == 1 ? "Product Verification" : "Installation Verification";
                string VerificationState = VerificationStatus == -1 ? "All" : VerificationStatus == 1 ? "Success" : "Fail";

                //get data for generate csv from spvlog.
                DataTable dataTable = _spvLog.GetDataForExportCSVForSpvLogs(ServiceAdministrator, ResellerId, SolarCompanyId, JobReferenceOrId, PVDSWHcode, SPVMethod, VerificationStatus, ResponseCode, Manufacturer, ModelNumber, SerialNumer, FromRequestDate, ToRequestDate);
                //generate csv of spvlog datatable.
                StringBuilder csv = new StringBuilder();
                csv.Append(Helper.Helper.Common.StringToCSVCell(ServiceAdministratorName) + ",");
                csv.Remove(csv.ToString().Length - 1, 1);
                csv.Append("\r\n");
                csv.Append(@"Reseller:" + ResellerName);
                csv.Append("\r\n");
                if (!IsWithoutSCA)
                {
                    csv.Append(@"Solar Company:" + SolarCompanyname);
                    csv.Append("\r\n");
                }
                csv.Append(@"Reference Number/Job ID Number:" + JobReferenceOrId);
                csv.Append("\r\n");
                csv.Append(@"PVD/SWH code:" + PVDSWHcode);
                csv.Append("\r\n");
                csv.Append(@"SPV Method:" + SpvMethod);
                csv.Append("\r\n");
                csv.Append(@"Verification Status:" + VerificationState);
                csv.Append("\r\n");
                csv.Append(@"Response Code:" + ResponseCode);
                csv.Append("\r\n");
                csv.Append(@"Manufacturer:" + Manufacturer);
                csv.Append("\r\n");
                csv.Append(@"Model Number:" + ModelNumber);
                csv.Append("\r\n");
                csv.Append(@"Serial Number:" + SerialNumer);
                csv.Append("\r\n");
                csv.Append(@"FromRequestDate:" + FromRequestDate);
                csv.Append("\r\n");
                csv.Append(@"ToRequestDate:" + ToRequestDate);
                csv.Append("\r\n");


                //id iswithout sca button click then remove solar company and reseller column from csv.
                if (!IsWithoutSCA)
                {
                    dataTable.Columns.Remove("SolarCompanyCode");
                    csv.Append(@"SolarCompanyName,ResellerName,JobId,SerialNumber,SpvMethod,VerificationStatus,ResponseCode,ResponseTime,ServiceAdministrator,RequestTime,Manufacturer,ModelNumber,Supllier,ResponseMessage");
                }
                else
                {
                    dataTable.Columns.Remove("CompanyName");
                    dataTable.Columns.Remove("ResellerName");
                    
                    csv.Append(@"SolarCompanyCode,JobId,SerialNumber,SpvMethod,VerificationStatus,ResponseCode,ResponseTime,ServiceAdministrator,RequestTime,Manufacturer,ModelNumber,Supllier,ResponseMessage");
                }
                csv.Append("\r\n");
                //var cnt = dataTable.Rows.Count;
                foreach (DataRow row in dataTable.Rows)
                {
                    foreach (string item in row.ItemArray)
                    {
                        csv.Append(Helper.Helper.Common.StringToCSVCell(item) + ",");
                    }

                    csv.Remove(csv.ToString().Length - 1, 1);
                    csv.Append("\r\n");
                }

                Response.Clear();
                Response.Buffer = true;
                Response.AddHeader("content-disposition", "attachment;filename=SpvLogs" + DateTime.Now.ToString() + ".csv");
                Response.Charset = "";
                Response.ContentType = "application/text";
                Response.Output.Write(csv.ToString());
                Response.Flush();
                Response.End();
            }

FormBot.Main/Views/SpvLog/Index.cshtml
@model FormBot.Entity.JobList
@using FormBot.Helper;
@{
    ViewBag.Title = "SPV PANELS LOGS";
    ViewBag.IsKendo = true;

}
<link href="~/Content/sumoselect.css" rel="stylesheet" />
<link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
<div class="container-fluid spv-log-listing">
    <div class="title">
        <div class="row">
            <h1 class="col-md-4" style="font-size: 25px; font-weight: 400; line-height: 20px ">SPV PANELS LOGS</h1>
        </div>
    </div>
    <div class="alert alert-success alert-dismissible" role="alert" id="errorMsgRegion" style="display: none">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    </div>
    <div class="joblisting_search">
        <div class="row">
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="form-group">
                    <label class="control-label">VSP service:</label>
                    <select class="report-search-box" id="txtVpsService" style="display:none;" multiple="multiple" placeholder="All VSP service"></select>
                </div>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="form-group">
                    <label class="control-label">Reseller:</label>
                    <select class="form-control" id="drpReseller" name="Reseller"></select>
                </div>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="form-group">
                    <label class="control-label">Solar Company:</label>
                    <input type="hidden" id="hdnsolarCompanyid" />
                    <input id="txtSolarCompany" name="SolarCompany" class="form-control " />
                </div>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="form-group">
                    <label class="control-label">Job reference / Job ID:</label>
                    <input type="text" id="txtReferenceNumberOrJobId" name="ReferenceNumberOrJobId" class="form-control" />
                </div>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="form-group">
                    <label class="control-label">PVD/SWH code:</label>
                    <input type="text" id="txtPvdOrSwhCode" name="PvdOrSwhCode" class="form-control" />
                </div>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="form-group">
                    <label class="control-label">SPV Method:</label>
                    <select class="form-control" id="drpSpvMethod" name="SpvMethod">
                        <option value="-1">All</option>
                        <option value="1">Product Verification</option>
                        <option value="2">Installation Verification</option>
                    </select>
                </div>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="form-group">
                    <label class="control-label">SPV Request Status:</label>
                    <select class="form-control" id="drpSpvRequestStatus" name="SpvRequestStatus">
                        <option value="-1">All</option>
                        <option value="1">Success</option>
                        <option value="2">Fail</option>
                    </select>
                </div>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="form-group">
                    <label class="control-label">Response Code:</label>
                    <input type="text" id="txtResponseCode" name="ResponseCode" class="form-control" />
                </div>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="form-group">
                    <label class="control-label">Serial Number:</label>
                    <input type="text" id="txtSerialNumber" name="SerialNumber" class="form-control" />
                </div>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="form-group">
                    <label class="control-label">Manufacturer:</label>
                    <input type="text" id="txtManufacturer" name="Manufacturer" class="form-control" />
                </div>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="form-group">
                    <label class="control-label">Model number:</label>
                    <input type="text" id="txtModelNumber" name="ModelNumber" class="form-control" />
                </div>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="form-group">
                    <label class="control-label">Requested Date Range:</label>
                    <div class="row">
                        <div class="col-xs-6">
                            <div class="input-group">
                                <input type="text" class="form-control" id="txtFromDateOrTime" placeholder="From">
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="input-group">
                                <input type="text" class="form-control" id="txtToDateOrTime" placeholder="To">
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group" style="margin-top: 10px;">
        <input type="button" id="btnSearch" class="primary search_ic" value="Search">
        <div class="default btn icon-btn">
            <span class="sprite-img reset_ic"></span>
            <input type="button" id="btnClear" class="" value="Clear">
        </div>
    </div>
   
    <div class="clearfix">
        @*<input type="button" id="btnCsvGenerate" class="primary search_ic" value="Export CSV">*@
        <button class="btn default export-ic" type="button" id="btnCsvGenerate"  style="float:right;margin-left:10px;">Export.csv - All Download</button>
        <button class="btn default export-ic" type="button" id="btnCsvGenerateWithOutSCA"  style="float:right;margin-left:10px;">Export.csv - Without SCA</button>
        <button class="default btn pull-right m-b-15 marg-r-0" id="collapse">Collapse All</button>
    </div>
    <!-- Grid start -->
    <div class="toggle-table-row kendo-grid">
        <div id="dtSpvLogs"></div>
    </div>
</div>
@section scripts{
    <script src="~/Scripts/jquery.nicescroll.min.js"></script>
    <script src="~/Scripts/View/Spv/spv.logs.js"></script>
    <script src="~/Scripts/jquery.sumoselect.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script>
        //Url Declaration
        var urlGetSolarCompanyByResellerId = '@Url.Action("GetSolarCompanyByResellerId","SolarCompany")',
            urlGetAllReseller = '@Url.Action("GetReseller","Reseller")',
            urlGetEndPoints = '@Url.Action("GetEndPointList","SpvLog")',
            urlGetSpvLogs = '@Url.Action("GetSpvLogs","SpvLog")',
            urlGetSpvLogDetails = '@Url.Action("GetSpvLogDetailsBySpvLogId","SpvLog")',
            dateFormat = '@FormBot.Helper.ProjectConfiguration.GetDateFormat',
            urlExportCSVForSPVLogs = '@Url.Action("ExportCSVForSPVLog", "SpvLog")'
            ;
    </script>
}